spring:
      datasource:
        url: jdbc:mysql://localhost:3306/mybatis_module?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 193510
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
      mapper-locations: classpath:mapper/*.xml  # 指定XML映射文件位置,使用注解法（如 @Select, @Insert 等）开发 MyBatis 映射器时，可以不需要配置此选项
      type-aliases-package: com.yourpackage.entity  # 实体类包路径,使用注解法（如 @Select, @Insert 等）开发 MyBatis 映射器时，可以不需要配置此选项
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志调试

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
 # params: count=countSql
